#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use VBoxCLI\Console\Command\Config;
use VBoxCLI\Console\Command\LS;
use VBoxCLI\Console\Command\Start;
use VBoxCLI\Console\Command\SSH;
use VBoxCLI\Console\Command\Suspend;
use VBoxCLI\Console\Command\License;

$app = new Application('VirtualBox Command Line Wrapper', '0.5.1');

$app->add(new Config());
$app->add(new LS());
$app->add(new Start());
$app->add(new SSH());
$app->add(new Suspend());
$app->add(new License());

$app->run();

// vim: syntax=php expandtab tabstop=4 shiftwidth=4 softtabstop=4:
