#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use XDMS\Console\Command\VMLS;
use XDMS\Console\Command\VMSSH;

$app = new Application('VirtualBox Command Line Wrapper', '0.2.1');

$app->add(new VMLS());
$app->add(new VMSSH());

$app->run();

// vim: syntax=php expandtab tabstop=4 shiftwidth=4 softtabstop=4:
