#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use XDMS\Console\Command\LS;
use XDMS\Console\Command\Start;
use XDMS\Console\Command\SSH;

$app = new Application('VirtualBox Command Line Wrapper', '0.2.1');

$app->add(new LS());
$app->add(new Start());
$app->add(new SSH());

$app->run();

// vim: syntax=php expandtab tabstop=4 shiftwidth=4 softtabstop=4:
