#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use XDMS\Console\Command\VMList;
use Symfony\Component\Console\Application;

$app = new Application('XDMS Command Line Tool', '1.0');

$app->add(new VMList());

$app->run();

// vim: syntax=php expandtab tabstop=4 shiftwidth=4 softtabstop=4:
